rails/attract_petition/config/routes.rb
Rails.application.routes.draw do

  root 'petitions#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'petitions/all' => 'petitions#all'

  resources :users
  resources :sessions
  resources :petitions

end

rails/attract_petition/app/models/petition.rb
class Petition < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true, length: { minimum: 5 }

end

rails/attract_petition/app/models/user.rb
class User < ActiveRecord::Base
  has_many :petitions

  has_secure_password

  validates :email, presence: true, email: true
  validates :first_name, presence: true, length: { in: 2..25 }
  validates :last_name, presence: true, length: { in: 2..25 }

  validates_uniqueness_of :email
end

rails/attract_petition/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    helper_method :current_user

    def authorize
      redirect_to login_url, alert: 'Требуется авторизация!' if current_user.nil?
    end
end

rails/attract_petition/app/controllers/petitions_controller.rb
class PetitionsController < ApplicationController

  before_filter :authorize, only: [:edit, :update, :destroy, :create, :new]

  def index
    @petitions = Petition.order(created_at: :desc).limit(10)
  end

  def show
    @petition = Petition.find(params[:id])
  end

  def new
    @petition = Petition.new
  end

  def edit
    @petition = Petition.find(params[:id])
  end

  def create
    @petition = current_user.petitions.create(petition_params)
    if @petition.save
      redirect_to @petition
    else
      render 'new'
    end
  end

  def update
    @petition = Petition.find(params[:id])

    if @petition.update(petition_params)
      redirect_to @petition
    else
      render 'edit'
    end
  end

  def destroy
    @petition = Petition.find(params[:id])
    @petition.destroy

    redirect_to petitions_path
  end

  def all
    @petitions = Petition.all
    @petitions = @petitions.where(user: current_user) if params[:my]
  end

  private
    def petition_params
      params.require(:petition).permit(:title, :description)
    end
end

rails/attract_petition/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])

    if (user && user.authenticate(params[:password]))
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Успешно авторизован!'
    else
      flash.now.alert = 'Не верный email или пароль'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Успешно вышел'
  end
end

rails/attract_petition/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Спасибо за регистрацию!'
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation)
    end
end

rails/attract_petition/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/attract_petition/app/helpers/petitions_helper.rb
module PetitionsHelper
end

rails/attract_petition/app/helpers/sessions_helper.rb
module SessionsHelper
end

rails/attract_petition/app/helpers/users_helper.rb
module UsersHelper
end

rails/attract_petition/app/views/application/_errors.html.erb
<% if validate_item.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% validate_item.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

rails/attract_petition/app/views/application/_right_menu.html.erb
<ul>
  <li><%= link_to 'Все петиции', petitions_all_path %></li>
  <li><%= link_to 'Создать петицию', new_petition_path %></li>

  <% if current_user  %>
    <li><%= link_to 'Мои петиции', petitions_all_path(my: true) %></li>
  <% end %>
</ul>

rails/attract_petition/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Petition</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="all_site">
  <header>
    <div class="logo"><%= link_to 'Логотип', root_path %></div>
    <div class="sign_menu">
      <% if current_user  %>
          <%= current_user.email %>(<%= link_to 'Выйти', logout_path %>)
      <% else %>
          <%= link_to 'Регистрация', signup_path %> |
          <%= link_to 'Войти', login_path %>
      <% end %>
    </div>
    <h1>Онлайн петиции</h1>
  </header>

  <div class="notices">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>
  </div>

  <div class="wrapper">
    <div id="content">
      <%= yield %>
    </div>
    <div id="right_menu">
      <%= render 'right_menu' %>
    </div>
    <div class="clear"></div>
  </div>

  <footer>
    <div class="copyright">
      Copyright © 2016 Ruby cources
      <span>ДЗ Фоменко Вячеслава</span>
      <div class="clear"></div>
    </div>
  </footer>
</div>
</body>
</html>

rails/attract_petition/app/views/petitions/_form.html.erb
<%= form_for @petition do |f| %>

    <p>
      <%= f.label :title, 'Название' %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :description, 'Описание' %><br>
      <%= f.text_area :description %>
    </p>

    <%= render 'errors', validate_item: @petition %>

    <p>
      <%= f.submit %>
    </p>

<% end %>

rails/attract_petition/app/views/petitions/_petitions_table.html.erb
<table border="1" width="100%">
  <tr>
    <th>Название</th>
    <th>Автор</th>
    <% if (current_user && params[:my]) %>
        <th colspan="2">Опции</th>
    <% end  %>
  </tr>

  <% @petitions.each do |petition| %>
      <tr>
        <td><%= link_to petition.title, petition_path(petition) %></td>
        <td><%= petition.user.first_name %> <%= petition.user.last_name %></td>

        <% if (current_user && params[:my]) %>
            <td><%= link_to 'Edit', edit_petition_path(petition) %></td>
            <td><%= link_to 'Delete', petition_path(petition),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
  <% end %>
</table>

rails/attract_petition/app/views/petitions/all.html.erb
<h2><%= params[:my]?'Мои':'Все' %> петиции</h2>

<%= render 'petitions_table' %>

rails/attract_petition/app/views/petitions/edit.html.erb
<h1>Редактирование предложения</h1>

<%= render 'form' %>

<%= link_to 'Back', petition_path %>

rails/attract_petition/app/views/petitions/index.html.erb
<h2>Последние петиции </h2>

<%= render 'petitions_table' %>

rails/attract_petition/app/views/petitions/new.html.erb
<h2>Новая петиция</h2>

<%= render 'form' %>

rails/attract_petition/app/views/petitions/show.html.erb
<h2>Петиция</h2>

<% if (current_user && @petition.user_id == current_user.id) %>
    <%= link_to 'Edit', edit_petition_path(@petition) %>
<% end  %>

<p>
  <strong><%= @petition.title %></strong>
</p>

<p>
    <%= @petition.description %>
</p>

rails/attract_petition/app/views/users/new.html.erb
<h2>Регистрация</h2>

<%= form_for @user do |f| %>
    <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div>
      <%= f.label :first_name, 'Имя'%>
      <%= f.text_field :first_name %>
    </div>

    <div>
      <%= f.label :last_name, 'Фамилия'%>
      <%= f.text_field :last_name %>
    </div>

    <div>
      <%= f.label :password, 'Пароль'%>
      <%= f.password_field :password %>
    </div>

    <div>
      <%= f.label :password_confirmation, 'Подтверждение пароля'%>
      <%= f.password_field :password_confirmation %>
    </div>

    <%= render 'errors', validate_item: @user %>

    <div>
      <%= f.submit('Зарегистрироваться') %>
    </div>
<% end %>